resources:
  containers:
  - container: ci
    image: sbx320/mtasa-blue-azure:latest

jobs:
- job: macOS
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - bash: brew install mysql
    displayName: 'Install MySQL'
  - script: ./linux-build.sh
    displayName: 'Run Build'

- job: linux
  pool:
    vmImage: 'Ubuntu 16.04'
  container: ci
  steps:
  - script: ./linux-build.sh
    displayName: 'Run Build'

- job: windows
  pool:
    vmImage: 'windows-2019'
  variables:
    solution: 'Build/MTASA.sln'
    buildConfiguration: 'Release'
  steps:
  - powershell: Invoke-WebRequest https://mirror.mtasa.com/bdata/DXFiles.zip -OutFile utils/DXFiles.zip
    displayName: 'Download DirectX'
  - powershell: Expand-Archive -Path utils/DXFiles.zip -DestinationPath utils/DXFiles
    displayName: 'Extract DirectX'
  - script: utils\premake5 install_cef
    displayName: 'Install CEF'
  - script: utils\premake5 vs2017
    env:
      DXSDK_DIR: './utils/DXFiles/'
      CI: 'true'
    displayName: 'Create Visual Studio 2017 Solution'
  - task: VSBuild@1
    inputs:
      solution: '$(solution)'
      configuration: '$(buildConfiguration)'
