name: Docker Image

on: 
  push:
    branches:
    - master
    paths: 
    - '.github/workflows/build.yaml'
    - '.github/workflows/dockerimage.yaml'
    - 'utils/compat/**'
    - 'Dockerfile'
    - 'Dockerfile.i386'
    - 'Dockerfile.armhf'
    - 'Dockerfile.arm64'
    - 'Dockerfile.osx-x64'
    - 'Dockerfile.osx-arm64'

jobs:
  build:
    strategy:
      matrix:
        include:
        - tag: latest
          dockerfile: Dockerfile
        - tag: i386
          dockerfile: Dockerfile.i386
        - tag: armhf
          dockerfile: Dockerfile.armhf
        - tag: arm64
          dockerfile: Dockerfile.arm64
        - tag: osx-x64
          dockerfile: Dockerfile.osx-x64
        - tag: osx-arm64
          dockerfile: Dockerfile.osx-arm64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CI_PAT }}
    - uses: docker/build-push-action@v5
      with:
        push: true
        file: ./${{ matrix.dockerfile }}
        tags: ghcr.io/multitheftauto/mtasa-blue-build:${{ matrix.tag }}
